# Generated by Django 2.2.6 on 2020-12-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryticketreply',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
