# Generated by Django 2.2.6 on 2020-12-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_year', models.IntegerField(default=0)),
                ('target_jan', models.IntegerField(default=0)),
                ('target_feb', models.IntegerField(default=0)),
                ('target_mar', models.IntegerField(default=0)),
                ('target_apr', models.IntegerField(default=0)),
                ('target_may', models.IntegerField(default=0)),
                ('target_jun', models.IntegerField(default=0)),
                ('target_jul', models.IntegerField(default=0)),
                ('target_aug', models.IntegerField(default=0)),
                ('target_sep', models.IntegerField(default=0)),
                ('target_oct', models.IntegerField(default=0)),
                ('target_nov', models.IntegerField(default=0)),
                ('target_dec', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
