# Generated by Django 2.2.6 on 2020-09-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBIDApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ROB', 'Registration of Business'), ('ROC', 'Registration of Company')], default='ROB', max_length=3)),
                ('product_type', models.CharField(choices=[('BT', 'Both'), ('LT', 'Listing'), ('PD', 'Product')], default='BT', max_length=2)),
                ('status', models.CharField(choices=[('PG', 'Pending'), ('PD', 'Paid')], default='PG', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
