apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: ssm-product-webapp
  name: ssm-product-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: ssm-product-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssm-product-webapp
    spec:
      containers:
      - image: syafiqpipe/ssm-product-webapp:1.0.10
        imagePullPolicy: Always   
        name: ssm-product-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30