# Generated by Django 2.2.12 on 2020-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_auto_20200519_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='diagram_type',
            field=models.CharField(choices=[('DP', 'Datatable'), ('PF', 'Process Flow'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
