# Generated by Django 2.2.6 on 2020-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200910_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='egov_request',
            field=models.CharField(choices=[('NA', 'NA'), ('AP', 'Approved'), ('PD', 'Pending')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='package',
            field=models.IntegerField(default=0),
        ),
    ]
