# Generated by Django 2.2.6 on 2020-09-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcbid_amount'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartcbid',
            name='products',
        ),
        migrations.AddField(
            model_name='cartcbid',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketCBID'),
        ),
    ]
