# Generated by Django 2.2.6 on 2020-09-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200913_0934'),
        ('transactions', '0003_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='entity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='entity_registration_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
