# Generated by Django 2.2.6 on 2020-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200925_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
