# Generated by Django 2.2.6 on 2020-09-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
