# Generated by Django 2.2.12 on 2020-05-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20200517_0808'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20200509_1657'),
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='class_type',
            field=models.CharField(choices=[('PR', 'Project'), ('SM', 'Submission'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='diagram',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagram',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
    ]
