# Generated by Django 2.2.6 on 2020-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='audit_firm_number',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='check_digit',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='outfit',
            name='company_number',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='company_number_new',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='registration_number_new',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='registration_number',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
