# Generated by Django 2.2.6 on 2020-09-13 09:34

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200913_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_letter_number', models.CharField(default='NA', max_length=100)),
                ('ip_no', models.CharField(default='NA', max_length=100)),
                ('court_case_number', models.CharField(default='NA', max_length=100)),
                ('official_attachment', models.FileField(null=True, upload_to=core.helpers.PathAndRename('investigation-attachment-official'))),
                ('offense', models.CharField(default='NA', max_length=100)),
                ('document_request', models.FileField(null=True, upload_to=core.helpers.PathAndRename('investigation-document-request'))),
                ('submit_request', models.FileField(null=True, upload_to=core.helpers.PathAndRename('investigation-submit-request'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCBID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ROB', 'Registration of Business'), ('ROC', 'Registration of Company')], default='ROB', max_length=3)),
                ('product_type', models.CharField(choices=[('BT', 'Both'), ('LT', 'Listing'), ('PD', 'Product')], default='BT', max_length=2)),
                ('status', models.CharField(choices=[('PG', 'Pending'), ('PD', 'Paid')], default='PG', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.TextField(default='NA')),
                ('topic_type', models.CharField(choices=[('PD', 'Product'), ('ID', 'Image Document'), ('WI', 'Web Issues'), ('OT', 'Others')], default='OT', max_length=2)),
                ('attached_document', models.FileField(null=True, upload_to=core.helpers.PathAndRename('enquiry-attached-document'))),
                ('error_screenshot', models.ImageField(null=True, upload_to=core.helpers.PathAndRename('enquiry-error-screenshot'))),
                ('error_supporting_document', models.FileField(null=True, upload_to=core.helpers.PathAndRename('enquiry-supporting-document'))),
                ('error_product', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
