# Generated by Django 2.2.6 on 2020-09-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcbid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
