# Generated by Django 2.2.6 on 2020-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200922_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='receipt_number',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
