# Generated by Django 2.2.6 on 2020-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcbid',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='ticketcbid',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcbid',
            name='pending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcbid',
            name='remarks',
            field=models.TextField(default='NA'),
        ),
    ]
