# Generated by Django 2.2.6 on 2020-09-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200922_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('RS', 'Resolved'), ('US', 'Unresolved')], default='US', max_length=2),
        ),
    ]
