# Generated by Django 2.2.6 on 2020-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='quota',
            field=models.IntegerField(default=0),
        ),
    ]
