# Generated by Django 2.2.6 on 2020-12-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201024_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('EG', 'eGovernment'), ('PB', 'Public'), ('FOC', 'FOC Account'), ('NA', 'Not Available')], default='PB', max_length=2),
        ),
    ]
